### ISSUE TITLE
The version of ParlAI?

### ISSUE THREAD

**Issue by RenzeLou** [skywalker023/focused-empathy#2]
Dear authors,

Thank you for your amazing work. However, some problems occurred when I tried to use your code:
`Job is running on ps
Traceback (most recent call last):
  File "/data/lourenze/ECD/baseline/focused-empathy/parlai/core/params.py", line 852, in add_task_args
    agent.add_cmdline_args(self, partial)
    │                      │     └ {'init_opt': None, 'allow_missing_init_opts': False, 'task': 'tasks.emocause', 'download_path': None, 'loglevel': 'info', 'datat...
    │                      └ ParlaiParser(prog='eval_emocause.py', usage=None, description='Evaluate a model', formatter_class=<class 'parlai.core.params.Cus...
    └ <class 'tasks.emocause.DefaultTeacher'>
TypeError: add_cmdline_args() takes 2 positional arguments but 3 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "eval_emocause.py", line 30, in <module>
    opt = parser.parse_args()
          └ ParlaiParser(prog='eval_emocause.py', usage=None, description='Evaluate a model', formatter_class=<class 'parlai.core.params.Cus...
  File "/data/lourenze/ECD/baseline/focused-empathy/parlai/core/params.py", line 1163, in parse_args
    self.add_extra_args(args)
    │                   └ None
    └ ParlaiParser(prog='eval_emocause.py', usage=None, description='Evaluate a model', formatter_class=<class 'parlai.core.params.Cus...
  File "/data/lourenze/ECD/baseline/focused-empathy/parlai/core/params.py", line 940, in add_extra_args
    self.add_task_args(task, partial)
    │                  │     └ {'init_opt': None, 'allow_missing_init_opts': False, 'task': 'tasks.emocause', 'download_path': None, 'loglevel': 'info', 'datat...
    │                  └ 'tasks.emocause'
    └ ParlaiParser(prog='eval_emocause.py', usage=None, description='Evaluate a model', formatter_class=<class 'parlai.core.params.Cus...
  File "/data/lourenze/ECD/baseline/focused-empathy/parlai/core/params.py", line 859, in add_task_args
    ) from typ
TypeError: Task 'tasks.emocause' appears to have signature add_cmdline_args(argparser) but we have updated the signature to add_cmdline_args(argparser, partial_opt). For details, see https://github.com/facebookresearch/ParlAI/pull/3328.`

It seems like the ParlAI had updated some signatures for 'add_cmdline_args', as can be seen at:
![image](https://user-images.githubusercontent.com/59914581/138053964-83128ec4-1082-402f-8100-294798a10087.png)

So, my question is what version of ParlAI did your work use? I try to use the latest version and v 1.0.0, it still didn't work.

Best regard

**Comment by skywalker023** [comment]
Hello Renze!
Thank you for taking interest in our paper!
Actually, if you follow the installation guide in the README, the required ParlAI version will be automatically installed!
The exact version of ParlAI we used is written here: https://github.com/skywalker023/focused-empathy/blob/04bdd0cf2fcd7bb4ee204cacb54ce970f426c916/environment.yml#L11
