### ISSUE TITLE
Multi GPU operation

### ISSUE THREAD

**Issue by 27182812** [skywalker023/focused-empathy#5]
Hello，my GPU is 16G，can I use multi GPU operation?

**Comment by skywalker023** [comment]
Hi!
Yes, I believe multi GPU is supported!
https://github.com/skywalker023/focused-empathy/blob/b8d6d801cb32d6289c68d05b992482cdaad01418/agents/empathetic_gee_blender.py#L149
For example, if you use 2 GPUs, Blender and GEE will be loaded to separate GPUs.
Hope this helps!

**Comment by 27182812** [comment]
Thank you for your reply. Do you mean that if I have multiple GPUs, it will recognize and run by itself? But I had multiple GPUs before, and then the memory overflowed.

**Comment by skywalker023** [comment]
Sorry for the really late response 😭
I'm currently going through a lot of deadlines... 
If you have multiple GPUs, that code will probably assign GEE and Blender on different GPUs.
I'm not completely sure. It may have been broken when I cleaned up the code for release.
Did you manage to run it on multi GPUs?

**Comment by 27182812** [comment]
I haven't tried yet. I tried to reduce the batch size.

**Comment by skywalker023** [comment]
I checked that it supports multi-gpu without any code modification!
The GEE and Blender are loaded on different GPUs.
Please feel free to re-open the issue if it doesn't work for you.
