### ISSUE TITLE
Interpretation & Exploration Scorer Training Process

### ISSUE THREAD

**Issue by kimwongyuda** [skywalker023/focused-empathy#6]
When you train Interpretation & Exploration Scorer,

is input of those just response?
otherwise, is input of those post and response?

**Comment by bckim92** [comment]
Hi! We use (seeker post, response) pairs to train empathy scorers. More details can be found in [here](https://github.com/behavioral-data/Empathy-Mental-Health). Thanks!

**Comment by kimwongyuda** [comment]
thanks for replying!
