### ISSUE TITLE
AssertionError: Checksum for gee_v1.tar.gz

### ISSUE THREAD

**Issue by jeremychang8** [skywalker023/focused-empathy#7]
I was trying to run the "eval_emocause.py", however, I got the following error:
> AssertionError: Checksum for gee_v1.tar.gz from
> 1TEKp3YRowAZju4UPXOSufqzU6j6_Z4wy
> does not match the expected checksum:
> 06d9b640bd7fa92528c6f3f4cd7715db593a0c1d3284151ba7f615f0d9c4989c != af0584e3c376dd364af0bbc122fea7303b9af52556f4dcbb0fbe8d6a136c0b2a

I followed all the instruction, including the environment creating. Not sure where it went wrong.

Btw, I'm really new to the ParlAI. Would you mind to give me some simple instructions for getting the emotional words with GEE?
For example, can I create the agent by using "DisplayModel.main"? 
How to use the "reason_emotion_causes" function after creating the agent?

I am looking forward to your reply, many thanks!

**Comment by skywalker023** [comment]
Hello Jeremy!

Have you tried the installation step-by-step?
I tried it myself with a fresh installation and there were no errors!
Perhaps you can give it a try again?
There can be errors if the download was suspended due to various reasons :)

I'm not sure I can give you exact guides for using the ParlAI, but I recommend you to use the function below for using GEE to infer emotion cause words!
https://github.com/skywalker023/focused-empathy/blob/04bdd0cf2fcd7bb4ee204cacb54ce970f426c916/agents/gee_agent.py#L196

Hope this helps!

**Comment by jeremychang8** [comment]
I've been trying this project since last time. 
The **hashcode of the model** seems to keep changing every time it is downloaded.
I have no clue whether the code or Google drive cause this issue.

> AssertionError: Checksum for gee_v1.tar.gz from
1TEKp3YRowAZju4UPXOSufqzU6j6_Z4wy
does not match the expected checksum:
**06d9b640bd7fa92528c6f3f4cd7715db593a0c1d3284151ba7f615f0d9c4989c** != af0584e3c376dd364af0bbc122fea7303b9af52556f4dcbb0fbe8d6a136c0b2a

> AssertionError: Checksum for gee_v1.tar.gz from
1TEKp3YRowAZju4UPXOSufqzU6j6_Z4wy
does not match the expected checksum:
**09c8aaec490c744b728bc67277fef8c6224d1ad9ab1fe036c5eddb9653b2d233** != af0584e3c376dd364af0bbc122fea7303b9af52556f4dcbb0fbe8d6a136c0b2a

What I have tried:
- Delete the data folder after it failed.
- Recreate the conda environment.
- Pip install update the Parlai.

My solution is download the GEE model and dataset manually, and place it in the right directory. 
Then, create my own .built flag to bypass the Checksum.
Hope it would help.

**Comment by jeremychang9** [comment]
Thanks for the reply! The issue has not been resolved yet.
The size of the downloaded file, gee_v1.tar.gz, is 2.15kb. 

>   File "focused-empathy-main/agents/gee_agent.py", line 31, in __init__
    download(opt['datapath'])
    │        └ {'init_opt': None, 'allow_missing_init_opts': False, 'task': 'tasks.emocause', 'download_path': None, 'loglevel': 'info', 'datat...
    └ <function download at 0x7f2b30875b90>
  File "/focused-empathy-main/zoo/gee/build.py", line 32, in download
    downloadable_file.download_file(dpath)
    │                               └ '/media/hd03/jeremychang8_data/focused-empathy-main/data/models/gee'
    └ <parlai.core.build_data.DownloadableFile object at 0x7f2b308738d0>

The Facebook research team seems to have the similar problem:
https://github.com/facebookresearch/mmf/issues/261
They bypass the checksum as the solution.

**Comment by skywalker023** [comment]
https://drive.google.com/uc?id=1TEKp3YRowAZju4UPXOSufqzU6j6_Z4wy&export=download&confirm=t
I replaced the GEE download link with the above. 
If you click the address, the download will start right away.
I personally bumped into the same issue as you and got it solved with the link above!
