### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by qu574** [skywalker023/focused-empathy#8]
Is there any code for training the model? Because I cannot find any code that describe about how to train the model using empathicdialogue dataset.

**Comment by skywalker023** [comment]
Hello!
Thanks for your interest in our project, and I'm sorry for the late response
Unfortunately, I have no bandwidth left to update the training code 😢
However, the training for GEE is pretty straightforward!
The input is the emotion label and the output is the emotional situation sentence.
I believe the HuggingFace code for training BART will be handy!
